packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/attribute-popup'
  - 'packages/center'
  - 'packages/collapsible-panel'
  - 'packages/export'
  - 'packages/legend'
  - 'packages/measure'
  - 'packages/menu'
  - 'packages/search'
  - 'packages/share'
  - 'packages/style-switcher'
  - 'packages/valhalla'
  - 'packages/*'