name: "Bug Report"
description: "Create a report to help us improve"
title: "[bug]:"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you report the bug, please make sure that:
        - You are using the latest version of the project. especially the `main` branch.
        - You have searched the [issues](https://github.com/watergis/svelte-maplibre-components/issues) for similar bug reports.
  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: bug-reproduction
    attributes:
      label: "Bug Reproduction"
      description: "A clear and concise description of how to reproduce the bug."
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: bug-screenshots
    attributes:
      label: "Bug Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false

  - type: textarea
    id: bug-system-information
    attributes:
      label: "Bug System Information"
      description: |
        If applicable, add information about your system configuration.
        Paste the output of `npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"`
      value: |
        - OS: [e.g. Windows 10]
        - Browser: [e.g. Google Chrome, Firefox]
    validations:
      required: false
